"""
Compute FID-50K and other metrics using PyTorch + clean-fid / torch-fidelity.

This replaces the original TensorFlow-based evaluator with a pure PyTorch
implementation.

Usage:
    # From .npz (generated by sample.py):
    python evaluator.py --ref-batch VIRTUAL_imagenet256_labeled.npz \
                        --sample-batch samples/samples_50000x256x256x3.npz

    # From a directory of PNGs:
    python evaluator.py --ref-path /path/to/imagenet/val \
                        --sample-path ./generated_images/

    # Compute FID using pytorch-fid (torch-fidelity backend):
    python evaluator.py --ref-batch ref.npz --sample-batch samples.npz --metric fid
"""

import argparse
import os
import tempfile
import warnings

import numpy as np
import torch
from scipy import linalg
from tqdm.auto import tqdm


def main():
    parser = argparse.ArgumentParser(description="Evaluate FID and other metrics")
    parser.add_argument("--ref-batch", type=str, default=None, help="Path to reference .npz file")
    parser.add_argument("--sample-batch", type=str, default=None, help="Path to sample .npz file")
    parser.add_argument("--ref-path", type=str, default=None, help="Path to reference image directory")
    parser.add_argument("--sample-path", type=str, default=None, help="Path to sample image directory")
    parser.add_argument("--batch-size", type=int, default=64, help="Batch size for feature extraction")
    parser.add_argument("--device", type=str, default="cuda", help="Device to use")
    parser.add_argument("--metric", type=str, default="all", choices=["all", "fid", "is"], help="Which metrics to compute")
    args = parser.parse_args()

    device = torch.device(args.device if torch.cuda.is_available() else "cpu")

    # Load inception model
    print("Loading InceptionV3 model...")
    inception = load_inception_model(device)

    # Process reference batch
    if args.ref_batch:
        print("Computing reference batch activations...")
        ref_acts = compute_activations_from_npz(args.ref_batch, inception, args.batch_size, device)
    elif args.ref_path:
        print("Computing reference activations from directory...")
        ref_acts = compute_activations_from_dir(args.ref_path, inception, args.batch_size, device)
    else:
        raise ValueError("Must specify either --ref-batch or --ref-path")

    # Process sample batch
    if args.sample_batch:
        print("Computing sample batch activations...")
        sample_acts = compute_activations_from_npz(args.sample_batch, inception, args.batch_size, device)
    elif args.sample_path:
        print("Computing sample activations from directory...")
        sample_acts = compute_activations_from_dir(args.sample_path, inception, args.batch_size, device)
    else:
        raise ValueError("Must specify either --sample-batch or --sample-path")

    # Compute metrics
    print("\nComputing evaluations...")

    if args.metric in ("all", "is"):
        is_score = compute_inception_score(sample_acts["logits"])
        print(f"Inception Score: {is_score:.4f}")

    if args.metric in ("all", "fid"):
        fid = compute_fid(ref_acts["pool"], sample_acts["pool"])
        print(f"FID: {fid:.4f}")

    if args.metric == "all":
        sfid = compute_fid(ref_acts["spatial"], sample_acts["spatial"])
        print(f"sFID: {sfid:.4f}")

        prec, recall = compute_precision_recall(ref_acts["pool"], sample_acts["pool"])
        print(f"Precision: {prec:.4f}")
        print(f"Recall: {recall:.4f}")


# ---------------------------------------------------------------------------
# Inception model
# ---------------------------------------------------------------------------

def load_inception_model(device):
    """Load InceptionV3 for FID computation using torchvision."""
    from torchvision.models import inception_v3, Inception_V3_Weights

    model = inception_v3(weights=Inception_V3_Weights.DEFAULT)
    model.eval()
    model.to(device)
    return model


class InceptionFeatureExtractor(torch.nn.Module):
    """Extract pool and spatial features from InceptionV3."""

    def __init__(self, model):
        super().__init__()
        self.model = model

    @torch.no_grad()
    def forward(self, x):
        # x: (N, 3, 299, 299) in [0, 1]
        # Inception expects (N, 3, 299, 299) normalized
        x = torch.nn.functional.interpolate(x, size=(299, 299), mode="bilinear", align_corners=False)
        # Normalize to ImageNet stats
        mean = torch.tensor([0.485, 0.456, 0.406], device=x.device).view(1, 3, 1, 1)
        std = torch.tensor([0.229, 0.224, 0.225], device=x.device).view(1, 3, 1, 1)
        x = (x - mean) / std

        # Run through inception up to the pool layer
        # Using internal layers
        m = self.model

        # N x 3 x 299 x 299
        x = m.Conv2d_1a_3x3(x)
        x = m.Conv2d_2a_3x3(x)
        x = m.Conv2d_2b_3x3(x)
        x = torch.nn.functional.max_pool2d(x, kernel_size=3, stride=2)
        x = m.Conv2d_3b_1x1(x)
        x = m.Conv2d_4a_3x3(x)
        x = torch.nn.functional.max_pool2d(x, kernel_size=3, stride=2)
        x = m.Mixed_5b(x)
        x = m.Mixed_5c(x)
        x = m.Mixed_5d(x)
        x = m.Mixed_6a(x)
        x = m.Mixed_6b(x)
        spatial = x  # spatial features for sFID
        x = m.Mixed_6c(x)
        x = m.Mixed_6d(x)
        x = m.Mixed_6e(x)
        x = m.Mixed_7a(x)
        x = m.Mixed_7b(x)
        x = m.Mixed_7c(x)

        # Pool features
        pool = torch.nn.functional.adaptive_avg_pool2d(x, (1, 1))
        pool = pool.flatten(1)  # (N, 2048)

        # Logits for IS
        logits = m.fc(pool)

        # Spatial features
        spatial = spatial.mean(dim=[-2, -1])  # (N, spatial_dim)

        return {
            "pool": pool,
            "spatial": spatial,
            "logits": logits,
        }


# ---------------------------------------------------------------------------
# Activations computation
# ---------------------------------------------------------------------------

@torch.no_grad()
def compute_activations_from_npz(npz_path, inception_model, batch_size, device):
    """Compute activations from an .npz file of images."""
    data = np.load(npz_path)
    images = data["arr_0"]  # (N, H, W, 3) uint8

    extractor = InceptionFeatureExtractor(inception_model)

    all_pool = []
    all_spatial = []
    all_logits = []

    for i in tqdm(range(0, len(images), batch_size), desc="Computing activations"):
        batch = images[i : i + batch_size]
        batch = torch.from_numpy(batch).float().permute(0, 3, 1, 2) / 255.0
        batch = batch.to(device)

        feats = extractor(batch)
        all_pool.append(feats["pool"].cpu().numpy())
        all_spatial.append(feats["spatial"].cpu().numpy())
        all_logits.append(feats["logits"].cpu().numpy())

    return {
        "pool": np.concatenate(all_pool, axis=0),
        "spatial": np.concatenate(all_spatial, axis=0),
        "logits": np.concatenate(all_logits, axis=0),
    }


@torch.no_grad()
def compute_activations_from_dir(dir_path, inception_model, batch_size, device):
    """Compute activations from a directory of images."""
    from PIL import Image
    from torchvision import transforms

    transform = transforms.Compose([
        transforms.Resize(299),
        transforms.CenterCrop(299),
        transforms.ToTensor(),
    ])

    image_files = sorted([
        os.path.join(dir_path, f) for f in os.listdir(dir_path)
        if f.lower().endswith((".png", ".jpg", ".jpeg"))
    ])

    extractor = InceptionFeatureExtractor(inception_model)

    all_pool = []
    all_spatial = []
    all_logits = []

    for i in tqdm(range(0, len(image_files), batch_size), desc="Computing activations"):
        batch_files = image_files[i : i + batch_size]
        batch = torch.stack([transform(Image.open(f).convert("RGB")) for f in batch_files])
        batch = batch.to(device)

        feats = extractor(batch)
        all_pool.append(feats["pool"].cpu().numpy())
        all_spatial.append(feats["spatial"].cpu().numpy())
        all_logits.append(feats["logits"].cpu().numpy())

    return {
        "pool": np.concatenate(all_pool, axis=0),
        "spatial": np.concatenate(all_spatial, axis=0),
        "logits": np.concatenate(all_logits, axis=0),
    }


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def compute_fid(acts1, acts2, eps=1e-6):
    """Compute Frechet Inception Distance between two sets of activations."""
    mu1 = np.mean(acts1, axis=0)
    sigma1 = np.cov(acts1, rowvar=False)
    mu2 = np.mean(acts2, axis=0)
    sigma2 = np.cov(acts2, rowvar=False)

    diff = mu1 - mu2
    covmean, _ = linalg.sqrtm(sigma1.dot(sigma2), disp=False)

    if not np.isfinite(covmean).all():
        warnings.warn("FID calculation produces singular product; adding eps to diagonal")
        offset = np.eye(sigma1.shape[0]) * eps
        covmean = linalg.sqrtm((sigma1 + offset).dot(sigma2 + offset))

    if np.iscomplexobj(covmean):
        if not np.allclose(np.diagonal(covmean).imag, 0, atol=1e-3):
            m = np.max(np.abs(covmean.imag))
            raise ValueError(f"Imaginary component {m}")
        covmean = covmean.real

    return float(diff.dot(diff) + np.trace(sigma1) + np.trace(sigma2) - 2 * np.trace(covmean))


def compute_inception_score(logits, split_size=5000):
    """Compute Inception Score from logits."""
    from scipy.special import softmax

    preds = softmax(logits, axis=1)
    scores = []
    for i in range(0, len(preds), split_size):
        part = preds[i : i + split_size]
        kl = part * (np.log(part + 1e-10) - np.log(np.expand_dims(np.mean(part, 0), 0) + 1e-10))
        kl = np.mean(np.sum(kl, 1))
        scores.append(np.exp(kl))
    return float(np.mean(scores))


def compute_precision_recall(ref_acts, sample_acts, k=3):
    """Compute precision and recall using k-NN manifold estimation."""
    # Compute pairwise distances and k-NN radii for reference
    ref_radii = _knn_radii(ref_acts, k)
    sample_radii = _knn_radii(sample_acts, k)

    # Precision: fraction of sample points within reference manifold
    precision = _manifold_coverage(ref_acts, ref_radii, sample_acts)

    # Recall: fraction of reference points within sample manifold
    recall = _manifold_coverage(sample_acts, sample_radii, ref_acts)

    return precision, recall


def _knn_radii(features, k=3, batch_size=10000):
    """Compute k-NN radius for each feature vector."""
    n = len(features)
    radii = np.zeros(n, dtype=np.float32)

    for i in range(0, n, batch_size):
        batch = features[i : i + batch_size]
        # Compute distances to all other features
        dists = np.sum((batch[:, None, :] - features[None, :, :]) ** 2, axis=-1)
        # Sort and get k-th nearest neighbor distance
        kth_dists = np.partition(dists, k + 1, axis=1)[:, k]
        radii[i : i + batch_size] = kth_dists

    return radii


def _manifold_coverage(ref_features, ref_radii, eval_features, batch_size=10000):
    """Check what fraction of eval_features are within ref manifold."""
    n_eval = len(eval_features)
    in_manifold = 0

    for i in range(0, n_eval, batch_size):
        batch = eval_features[i : i + batch_size]
        dists = np.sum((batch[:, None, :] - ref_features[None, :, :]) ** 2, axis=-1)
        in_manifold += np.sum(np.any(dists <= ref_radii[None, :], axis=1))

    return in_manifold / n_eval


if __name__ == "__main__":
    main()
