"""
Compute FID-50K and other metrics using PyTorch + clean-fid / torch-fidelity.

This replaces the original TensorFlow-based evaluator with a pure PyTorch
implementation.

Usage:
    # From .npz (generated by diffit-sample):
    diffit-eval --ref-batch VIRTUAL_imagenet256_labeled.npz \
                --sample-batch samples/samples_50000x256x256x3.npz

    # From a directory of PNGs:
    diffit-eval --ref-path /path/to/imagenet/val \
                --sample-path ./generated_images/

    # FID only:
    diffit-eval --ref-batch ref.npz --sample-batch samples.npz --metric fid
"""

import os
import warnings

import click
import numpy as np
import torch
from scipy import linalg
from tqdm.auto import tqdm

from diffit.constants import UINT8_MAX
from diffit.inception import InceptionFeatureExtractor, load_inception_model


@click.command()
@click.option("--ref-batch", type=str, default=None, help="Reference .npz batch")
@click.option("--ref-path", type=str, default=None, help="Reference image directory")
@click.option("--sample-batch", type=str, default=None, help="Sample .npz batch")
@click.option("--sample-path", type=str, default=None, help="Sample image directory")
@click.option("--batch-size", type=int, default=64, show_default=True, help="Feature-extraction batch size")
@click.option("--device", "device_str", type=str, default="cuda", show_default=True, help="Torch device")
@click.option("--metric", type=click.Choice(["all", "fid", "is"]), default="all", show_default=True,
              help="Which metrics to compute")
def main(ref_batch, ref_path, sample_batch, sample_path, batch_size, device_str, metric):
    """Evaluate FID / sFID / IS / precision / recall on bulk .npz or PNG batches.

    Legacy upstream-paper protocol. For WC-Co work the in-training combra metrics and
    `diffit-gen-images` -> the angle pipeline are the evaluation path.
    """
    device = torch.device(device_str if torch.cuda.is_available() else "cpu")

    print("Loading InceptionV3 model...")
    inception = load_inception_model(device)

    if ref_batch:
        print("Computing reference batch activations...")
        ref_acts = compute_activations_from_npz(ref_batch, inception, batch_size, device)
    elif ref_path:
        print("Computing reference activations from directory...")
        ref_acts = compute_activations_from_dir(ref_path, inception, batch_size, device)
    else:
        raise click.UsageError("Must specify either --ref-batch or --ref-path")

    if sample_batch:
        print("Computing sample batch activations...")
        sample_acts = compute_activations_from_npz(sample_batch, inception, batch_size, device)
    elif sample_path:
        print("Computing sample activations from directory...")
        sample_acts = compute_activations_from_dir(sample_path, inception, batch_size, device)
    else:
        raise click.UsageError("Must specify either --sample-batch or --sample-path")

    print("\nComputing evaluations...")

    if metric in ("all", "is"):
        print(f"Inception Score: {compute_inception_score(sample_acts['logits']):.4f}")

    if metric in ("all", "fid"):
        print(f"FID: {compute_fid(ref_acts['pool'], sample_acts['pool']):.4f}")

    if metric == "all":
        print(f"sFID: {compute_fid(ref_acts['spatial'], sample_acts['spatial']):.4f}")
        prec, recall = compute_precision_recall(ref_acts["pool"], sample_acts["pool"])
        print(f"Precision: {prec:.4f}")
        print(f"Recall: {recall:.4f}")


# ---------------------------------------------------------------------------
# Activations computation
#
# The InceptionV3 loader and feature extractor live in ``diffit/inception.py``
# so this standalone evaluator and the inline training metrics share one
# implementation.
# ---------------------------------------------------------------------------

@torch.no_grad()
def compute_activations_from_npz(npz_path, inception_model, batch_size, device):
    """Compute activations from an .npz file of images."""
    data = np.load(npz_path)
    images = data["arr_0"]  # (N, H, W, 3) uint8

    extractor = InceptionFeatureExtractor(inception_model)

    all_pool = []
    all_spatial = []
    all_logits = []

    for i in tqdm(range(0, len(images), batch_size), desc="Computing activations"):
        batch = images[i : i + batch_size]
        batch = torch.from_numpy(batch).float().permute(0, 3, 1, 2) / UINT8_MAX
        batch = batch.to(device)

        feats = extractor(batch)
        all_pool.append(feats["pool"].cpu().numpy())
        all_spatial.append(feats["spatial"].cpu().numpy())
        all_logits.append(feats["logits"].cpu().numpy())

    return {
        "pool": np.concatenate(all_pool, axis=0),
        "spatial": np.concatenate(all_spatial, axis=0),
        "logits": np.concatenate(all_logits, axis=0),
    }


@torch.no_grad()
def compute_activations_from_dir(dir_path, inception_model, batch_size, device):
    """Compute activations from a directory of images."""
    from PIL import Image
    from torchvision import transforms

    transform = transforms.Compose([
        transforms.Resize(299),
        transforms.CenterCrop(299),
        transforms.ToTensor(),
    ])

    image_files = sorted([
        os.path.join(dir_path, f) for f in os.listdir(dir_path)
        if f.lower().endswith((".png", ".jpg", ".jpeg"))
    ])

    extractor = InceptionFeatureExtractor(inception_model)

    all_pool = []
    all_spatial = []
    all_logits = []

    for i in tqdm(range(0, len(image_files), batch_size), desc="Computing activations"):
        batch_files = image_files[i : i + batch_size]
        batch = torch.stack([transform(Image.open(f).convert("RGB")) for f in batch_files])
        batch = batch.to(device)

        feats = extractor(batch)
        all_pool.append(feats["pool"].cpu().numpy())
        all_spatial.append(feats["spatial"].cpu().numpy())
        all_logits.append(feats["logits"].cpu().numpy())

    return {
        "pool": np.concatenate(all_pool, axis=0),
        "spatial": np.concatenate(all_spatial, axis=0),
        "logits": np.concatenate(all_logits, axis=0),
    }


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def compute_fid(acts1, acts2, eps=1e-6):
    """Compute Frechet Inception Distance between two sets of activations."""
    mu1 = np.mean(acts1, axis=0)
    sigma1 = np.cov(acts1, rowvar=False)
    mu2 = np.mean(acts2, axis=0)
    sigma2 = np.cov(acts2, rowvar=False)

    diff = mu1 - mu2
    covmean, _ = linalg.sqrtm(sigma1.dot(sigma2), disp=False)

    if not np.isfinite(covmean).all():
        warnings.warn("FID calculation produces singular product; adding eps to diagonal")
        offset = np.eye(sigma1.shape[0]) * eps
        covmean = linalg.sqrtm((sigma1 + offset).dot(sigma2 + offset))

    if np.iscomplexobj(covmean):
        if not np.allclose(np.diagonal(covmean).imag, 0, atol=1e-3):
            m = np.max(np.abs(covmean.imag))
            raise ValueError(f"Imaginary component {m}")
        covmean = covmean.real

    return float(diff.dot(diff) + np.trace(sigma1) + np.trace(sigma2) - 2 * np.trace(covmean))


def compute_inception_score(logits, split_size=5000):
    """Compute Inception Score from logits."""
    from scipy.special import softmax

    preds = softmax(logits, axis=1)
    scores = []
    for i in range(0, len(preds), split_size):
        part = preds[i : i + split_size]
        kl = part * (np.log(part + 1e-10) - np.log(np.expand_dims(np.mean(part, 0), 0) + 1e-10))
        kl = np.mean(np.sum(kl, 1))
        scores.append(np.exp(kl))
    return float(np.mean(scores))


def compute_precision_recall(ref_acts, sample_acts, k=3):
    """Compute precision and recall using k-NN manifold estimation."""
    # Compute pairwise distances and k-NN radii for reference
    ref_radii = _knn_radii(ref_acts, k)
    sample_radii = _knn_radii(sample_acts, k)

    # Precision: fraction of sample points within reference manifold
    precision = _manifold_coverage(ref_acts, ref_radii, sample_acts)

    # Recall: fraction of reference points within sample manifold
    recall = _manifold_coverage(sample_acts, sample_radii, ref_acts)

    return precision, recall


def _knn_radii(features, k=3, batch_size=10000):
    """Compute k-NN radius for each feature vector."""
    n = len(features)
    radii = np.zeros(n, dtype=np.float32)

    for i in range(0, n, batch_size):
        batch = features[i : i + batch_size]
        # Compute distances to all other features
        dists = np.sum((batch[:, None, :] - features[None, :, :]) ** 2, axis=-1)
        # Sort and get k-th nearest neighbor distance
        kth_dists = np.partition(dists, k + 1, axis=1)[:, k]
        radii[i : i + batch_size] = kth_dists

    return radii


def _manifold_coverage(ref_features, ref_radii, eval_features, batch_size=10000):
    """Check what fraction of eval_features are within ref manifold."""
    n_eval = len(eval_features)
    in_manifold = 0

    for i in range(0, n_eval, batch_size):
        batch = eval_features[i : i + batch_size]
        dists = np.sum((batch[:, None, :] - ref_features[None, :, :]) ** 2, axis=-1)
        in_manifold += np.sum(np.any(dists <= ref_radii[None, :], axis=1))

    return in_manifold / n_eval


if __name__ == "__main__":
    main()
